sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t deeptinair/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true deepttinair/docker-react npm run test